--* CURDATE()/CURRENT_DATE()

SELECT CURDATE() "DATE";

--* NOW() 
SELECT NOW();

--* DATE()

SELECT DATE("2025-12-06 22:04:18");
--* MONTH()
SELECT MONTH("2025-12-06 22:04:18");
--* MONTHNAME()
SELECT MONTHNAME("2025-12-06 22:04:18");

SELECT UPPER(LEFT(MONTHNAME(NOW()), 3));

--* DAY()
--* YEAR()
--* DAYNAME() .. monday

--* DAYOFMONTH()
--* DAYOFWEEK()
--* DAYOFYEAR()
--* WEEKOFMONTH()
--* WEEKOFYEAR()

SELECT DAYOFMONTH(NOW()); -- tarikh pe tarikh
SELECT DAYOFWEEK(NOW()); -- sunday se saturday... 1 se 7
SELECT DAYOFYEAR(NOW());
SELECT WEEKDAY(NOW()); -- monday se sunday... 0 se 6
SELECT WEEKOFYEAR(NOW());


--* SYSDATE()

SELECT NOW(), SLEEP(2), NOW();
SELECT TIME(SYSDATE()), SLEEP(2), TIME(SYSDATE());